---

# `defaults read` commands fail with exit status 255 if invoked improperly, but
# 1 for non-fatal problems, such as missing values.

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
- name: defaults | close open System Preferences panes
  command: osascript -e 'tell application "System Preferences" to quit'

# Many of these settings taken (or modified) from:
#
#   https://github.com/mathiasbynens/dotfiles/blob/master/.macos
#   https://github.com/wincent/wincent/blob/master/roles/defaults/tasks/main.yml
#

###############################################################################
# Dock                                                                        #
###############################################################################

# Only wipe all (default) app icons from the Dock when setting up a new Mac
- name: macdefaults | check if ~/.dockinit exists
  stat:
    path: '{{ ansible_env.HOME }}/.dockinit'
  register: dockinit_check
- name: macdefaults | wipe the default Dock icons
  command: defaults write com.apple.dock persistent-apps -array
  when: dockinit_check.stat.exists == False
- name: macdefaults | create the ~/.dockinit file now that the Dock icons have been wiped
  file:
    path: '{{ ansible_env.HOME }}/.dockinit'
    state: touch
  when: dockinit_check.stat.exists == False

# Last tested: [10.12.6]
- name: macdefaults | enable highlight hover effect for the grid view of a stack (Dock)
  osx_defaults: domain=com.apple.dock key=mouse-over-hilite-stack type=bool value=true

# Last tested: [10.12.6]
- name: macdefaults | set the icon size of Dock items to 64 pixels
  osx_defaults: domain=com.apple.dock key=tilesize type=int value=64

# Last tested: [10.12.6]
- name: macdefaults | System Preferences -> Dock -> Minimize windows using Scale effect
  osx_defaults: domain=com.apple.dock key=mineffect type=string value=scale

# Last tested: [10.12.6]
- name: macdefaults | System Preferences -> Dock -> Minimize windows into application icon
  osx_defaults: domain=com.apple.dock key=minimize-to-application type=bool value=true

# Last tested: [10.12.6]
- name: macdefaults | System Preferences -> Dock -> Show indicators for open applications
  osx_defaults: domain=com.apple.dock key=show-process-indicators type=bool value=true

# Last tested: [10.12.6]
- name: macdefaults | System Preferences -> Dock -> Automatically hide and show Dock
  osx_defaults: domain=com.apple.dock key=autohide type=bool value=true

###############################################################################
# Input devices                                                               #
###############################################################################

# Last tested [10.12.6]
- name: macdefaults | System Preferences -> Trackpad -> Point & Click -> Tap to click (Tap with one finger) - built-in Trackpad
  command: defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
- name: macdefaults | System Preferences -> Trackpad -> Point & Click -> Tap to click (Tap with one finger) - external Trackpad
  command: defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true

# Last tested [10.12.6]
- name: macdefaults | enable tap to click (Trackpad) for the login screen
  osx_defaults: domain=NSGlobalDomain host=currentHost key=com.apple.mouse.tapBehavior type=int value=1
- name: macdefaults | enable tap to click (Trackpad) for this user
  osx_defaults: domain=NSGlobalDomain key=com.apple.mouse.tapBehavior type=int value=1

# Last tested [10.12.6]
- name: macdefaults | System Preferences -> Accessibility -> Mouse & Trackpad -> Trackpad Options -> Enable dragging (with drag lock) - built-in Trackpad
  command: defaults write com.apple.AppleMultitouchTrackpad DragLock -bool true
- name: macdefaults | System Preferences -> Accessibility -> Mouse & Trackpad -> Trackpad Options -> Enable dragging (with drag lock) - built-in Trackpad
  command: defaults write com.apple.AppleMultitouchTrackpad Dragging -bool true
- name: macdefaults | System Preferences -> Accessibility -> Mouse & Trackpad -> Trackpad Options -> Enable dragging (with drag lock) - external Trackpad
  command: defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad DragLock -bool true
- name: macdefaults | System Preferences -> Accessibility -> Mouse & Trackpad -> Trackpad Options -> Enable dragging (with drag lock) - external Trackpad
  command: defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Dragging -bool true
