---
- name: shell | gets the fish path
  shell: which fish
  register: bin_fish

- name: shell | add fish binary to /etc/shells
  lineinfile:
    path: /etc/shells
    line: '{{ bin_fish.stdout }}'
    owner: root
    group: wheel
  become: true

- name: shell | check if user's default shell is already set to fish
  command: dscl . -read /Users/{{ ansible_env.USER }} UserShell
  register: current_shell

- name: shell | set homebrew fish as default shell
  command: dscl . -create /Users/{{ ansible_env.USER }} UserShell {{ bin_fish.stdout }}
  when: is_macos and ("fish" not in current_shell.stdout)
  become: true
