---
- name: shell | gets the fish path
  shell: which fish
  register: bin_fish

- name: shell | add fish binary to /etc/shells
  lineinfile:
    path: /etc/shells
    line: '{{ bin_fish.stdout }}'
    owner: root
    group: wheel
  become: true

- name: Set Homebrew fish as default shell
  command: dscl . -{{ item }}
  with_items:
    - create /Users/{{ ansible_env.USER }} UserShell {{ bin_fish.stdout }}
  when: is_macos
  become: true
