---
- name: Ensure .gnupg directory exists
  file:
    path: ~/.gnupg
    state: directory
    mode: 0700

- name: gnupg | generate and write gpg-agent.conf
  copy: src={{ playbook_dir }}/roles/dotfiles/files/gpg/{{ item }}
        dest=~/.gnupg/{{ item }}
  with_items:
    - gpg-agent.conf
    - gpg.conf
