---
- hosts: localhost
  roles:
    - { role: mas, tags: mas }
    - { role: homebrew, tags: homebrew }
    - { role: shell, tags: shell }
    - { role: browsers, tags: browsers }
    - { role: macdefaults, tags: macdefaults }
  vars:
    - is_macos: ansible_os_family == 'Darwin'
