---
- name: fish | set dotfiles directory
  shell: set -Ux DOTFILES {{ playbook_dir }}/roles/dotfiles/files
  args:
    executable: /opt/homebrew/bin/fish

- name: fish | set development projects directory
  shell: set -Ux PROJECTS {{ directories.dev_projects }}
  args:
    executable: /opt/homebrew/bin/fish

- name: fish | set code editors
  shell: set -Ux {{ item }}
  args:
    executable: /opt/homebrew/bin/fish
  with_items:
    - EDITOR {{ default_editor.shell }}
    - VISUAL {{ default_editor.visual }}