---
- name: fish | set dotfiles directory
  shell: set -Ux DOTFILES {{ playbook_dir }}/roles/dotfiles/files
  args:
    executable: /opt/homebrew/bin/fish

- name: fish | set development projects directory
  shell: set -Ux PROJECTS {{ directories.dev_projects }}
  args:
    executable: /opt/homebrew/bin/fish

- name: fish | set code editors
  shell: set -Ux {{ item }}
  args:
    executable: /opt/homebrew/bin/fish
  with_items:
    - EDITOR {{ default_editor.shell }}
    - VISUAL {{ default_editor.visual }}

- name: fish | clear fish greeting
  shell: set -U fish_greeting
  args:
    executable: /opt/homebrew/bin/fish

###############################################################################
# Find install scripts and execute them
###############################################################################

- name: fish | find install.fish scripts
  find:
    file_type: any
    paths: "{{ playbook_dir }}/roles/dotfiles/files"
    patterns: "install.fish"
    recurse: yes
  register: find_file_install_fish

- name: fish | execute install.fish scripts
  shell: "{{ item.path }}"
  args:
    executable: /opt/homebrew/bin/fish
  with_items: "{{find_file_install_fish.files}}"