---
- name: kitty | create kitty config directory
  file:
    path: "{{ directories.dotconfig }}/kitty"
    state: directory

- name: kitty | create symlinks for application settings
  file:
    src: "{{ playbook_dir }}/roles/dotfiles/files/kitty/{{ item }}"
    path: "{{ directories.dotconfig }}/kitty/{{ item }}"
    state: link
    force: yes
  with_items:
    - macos-launch-services-cmdline
    - kitty.conf

- name: kitty | download dark night theme
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/frankhinek/kitty-themes/main/dark-night.conf
    dest: "{{ directories.dotconfig }}/kitty/dark-night.conf"

- name: kitty | download alternate icon file
  ansible.builtin.get_url:
    url: https://github.com/frankhinek/kitty-icon/raw/main/kitty.icns
    dest: "{{ directories.dotconfig }}/kitty/kitty.icns"

- name: kitty | set alternative icon for kitty app
  ansible.builtin.shell: "fileicon set /Applications/kitty.app {{ directories.dotconfig }}/kitty/kitty.icns"
  args:
    executable: "{{ paths.fish }}"