---
- name: mas | ensure MAS is installed
  homebrew: name=mas state=present

- name: mas | list installed MAS apps
  command: mas list
  register: mas_list
  check_mode: no
  changed_when: false

- name: mas | ensure MAS apps suitable for all macOS systems are installed
  command: mas install "{{ item.id }}"
  with_items: "{{ mas_installed_apps.all }}"
  when: item.id|string not in mas_list.stdout

- name: mas | ensure MAS apps suitable for personal macOS systems are installed
  command: mas install "{{ item.id }}"
  with_items: "{{ mas_installed_apps.personal }}"
  when:
    - "'personal' in group_names"
    - item.id|string not in mas_list.stdout

- name: mas | ensure MAS apps suitable for work macOS systems are installed
  command: mas install "{{ item.id }}"
  with_items: "{{ mas_installed_apps.work }}"
  when:
    - "'work' in group_names"
    - item.id|string not in mas_list.stdout

- name: mas | upgrade all apps (if configured)
  command: mas upgrade
  when: mas_upgrade_all_apps

###############################################################################
# Run other tasks that are part of the role
###############################################################################

- include_tasks: automounter-helper.yml
  when:
    - "'personal' in group_names"