---
- name: homebrew | download Homebrew install script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: vendor/homebrew/install.sh
    mode: 'u+rx'

- name: homebrew | install Homebrew
  shell: vendor/homebrew/install.sh creates=/usr/local/bin/brew

- name: homebrew | update Homebrew
  homebrew: update_homebrew=yes

- name: homebrew | tap bundle
  homebrew_tap: tap=homebrew/bundle state=present

- name: homebrew | prepare Brewfile
  template: dest="~/Library/Preferences/Brewfile" mode=0644 src=Brewfile

- name: homebrew | bundle
  command: brew bundle chdir="~/Library/Preferences"

- name: homebrew | clean up old versions
  command: brew cleanup
