---
mas_installed_apps:
  all:
    - { id: 408981434, name: "iMovie (10.3.5)" }
    - { id: 409183694, name: "Keynote (12.1)" }
    - { id: 441258766, name: "Magnet (2.9.0)" }
    - { id: 409203825, name: "Numbers (12.1)" }
    - { id: 409201541, name: "Pages (11.2)" }
  personal:
    - { id: 1055511498, name: "Day One (2.7.4)" }
  work:
    - { id: 1, name: "None"}

mas_upgrade_all_apps: no